# Directories
data_dir: "black_scholes_simulated_data"
model_dir: "run_?"

# Prediction & Update Control
prediction_horizon: 1  # How many steps to predict into the future at each iteration.
sindy_update_every: 500  # Number of steps before re-discovering the SINDy model.
nn_update_every: 20000  # Number of steps before retraining the neural network.

retrain_evals: 500

# Confidence Interval Control
calculate_intervals: True
confidence_level: 0.95

# Data hyperparameters (when updating model)
N_u: 125000
N_f: 87500

# Training hyperparameters (when updating model)
w_data: 1.0
w_physics: 1.0
w_l1: 0.0
display_every: 100