# Simulation hyperparameters
T: 1.0
N_SIM: 250000
R: 0.3
K: 102.0
S0: 100.0
SIGMA_VAL: 0.2

# Data split point
NUM_UNHIDDEN_POINTS: 150000

# Reproducibility
seed: 42

# Output configuration
output_dir_name: "black_scholes_simulated_data"