# Data options
data_dir: "black_scholes_simulated_data"
uniform_t: True

# Data hyperparameters
N_u: 125000
N_f: 87500

# Model hyperparameters
layers: [2, 32, 32, 32, 32, 32, 32, 1]  # If passed as override, enter as 2,32,32,32,32,32,32,1

# Training hyperparameters
# Loss function weights
w_data: 1.0
w_physics: 1.0
w_l1: 0.00000001

# Optimizer
max_eval: 3_000
patience: 3

display_every: 100